---
title: Das Miscellany
author: Alan Davies
description: Musings on software, math, guitars and more ...
copyright: Alan Davies 2017
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
---
